included: # 린트 과정에 포함할 파일 경로.

excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
  
disabled_rules: # 실행에서 제외할 룰 식별자들
    - trailing_whitespace # 행 끝의 공백
    - force_cast # 강제 캐스팅
        
line_length: # 코드 길이 제한
    warning: 200
    error: 250
    ignores_comments: true
    ignores_urls: true

file_length: # 코드 라인수 제한
    warning: 500
    error: 800
    
todo: # TODO, FIXME 미해결 확인
    included: ".*.swift"
    match_kinds: comment
    severity: warning

opt_in_rules: # 옵트 인 룰
    - empty_count # isEmpty 사용
    - explicit_init # 구조체, 클래스의 initialize를 명시적으로 선언 .init() 불가능
    - contains_over_first_not_nil
    - closure_end_indentation # 클로저의 종료 괄호는 클로저를 시작한는 줄과 동일한 수준으로 들여쓰기
    - discouraged_optional_boolean # Bool을 옵셔널하게 선언하면 안됨
    - legacy_random # Swift 4.2 이상부터 arc4random -> Int.random으로 작성
    - switch_case_on_newline # case 와 : 사이에 새 줄을 넣는 것을 선호
    - force_try
    - force_unwrapping

force_unwrapping: error # 암시적으로 지정
force_try:
    severity: warning # 명시적으로 지정

# 타입 이름의 길이를 제한
type_name:
    allowed_symbols: "Here_Hear"
    min_length: 1    # 최소 길이
    max_length:      # 최대 길이
        warning: 50    # 최대 길이를 초과할 경우 경고
        error: 60      # 최대 길이를 초과할 경우 에러
    excluded: ["Interface", "Repository", "Service"] # 이름 길이 제한에서 제외할 특정 타입 이름

# 변수, 상수, 함수 등의 식별자 이름의 길이를 제한
identifier_name:
    min_length: 1    # 최소 길이
    max_length:      # 최대 길이
        warning: 50    # 최대 길이를 초과할 경우 경고
        error: 60      # 최대 길이를 초과할 경우 에러
    excluded: [] # 이름 길이 제한에서 제외할 특정 식별자 이름

# 함수의 본문 길이
function_body_length:
    warning: 40 #15 -> 28줄 수정
    error: 70
    
# 함수의 복잡성(조건문, 반복문 등의 중첩)를 제한합니다
cyclomatic_complexity:
    warning: 10    # 복잡도가 10를 초과할 경우 경고 (6을 초과할 때 에서 10으로 변경)
    error: 15      # 복잡도가 15를 초과할 경우 에러
    

# 보고 유형
reporter: "xcode"
